// <auto-generated />
using UnityEngine;

namespace NappyCat.Pool
{
    /// <summary>
    /// Base MonoBehaviour that participates in pooling lifecycles.
    /// </summary>
    public class NcPooledBehaviour : MonoBehaviour
    {
        /// <summary>
        /// TODO: Called when behaviour is fetched from pool.
        /// </summary>
        public virtual void OnPoolAcquire()
        {
            // TODO: Reset state.
        }

        /// <summary>
        /// TODO: Called when behaviour is recycled.
        /// </summary>
        public virtual void OnPoolRelease()
        {
            // TODO: Clean-up state to avoid leaks.
        }
    }
}
