// <auto-generated />
using UnityEngine;

namespace NappyCat.Pool
{
    /// <summary>
    /// Configures pooling warm sizes, growth, and cull policies.
    /// </summary>
    [UnityEngine.CreateAssetMenu(menuName = "Nappy Cat/Pool/NcPool Policy")]
    public class NcPoolPolicySO : ScriptableObject
    {
        [UnityEngine.SerializeField]
        private int _warmCapacity = 8;

        /// <summary>
        /// Gets the initial warm capacity.
        /// </summary>
        public int WarmCapacity => _warmCapacity;
    }
}
