#if UNITY_EDITOR
// <auto-generated />
using UnityEditor;

namespace NappyCat.Pool.Editor
{
    /// <summary>
    /// Custom inspector for NcPoolPolicy assets.
    /// </summary>
    public class NcPoolInspector : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            UnityEditor.EditorGUILayout.HelpBox("TODO: Display runtime pool statistics.", UnityEditor.MessageType.Info);
        }
    }
}
#endif

